version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=toyokumo
      - POSTGRES_PASSWORD=commons
      - POSTGRES_DB=toyokumo
    volumes:
      - toyokumocommons-postgres:/var/lib/postgresql/data
    container_name: toyokumocommons-postgres
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - toyokumocommons-redis:/data
    container_name: toyokumocommons-redis

volumes:
  toyokumocommons-postgres:
  toyokumocommons-redis:
